<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BGR644L7R1" failures="1" tests="4" name="com.danube.qa.testcases.LoginPageTest" time="20.923" errors="0" timestamp="09 May 2019 13:53:23 GMT" skipped="3">
  <testcase classname="com.danube.qa.testcases.LoginPageTest" name="loginPageTitleTest" time="6.420">
    <failure message="expected [Cheap hotels, flights and holidays from Travel Republic] but found [Service Unavailable]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Cheap hotels, flights and holidays from Travel Republic] but found [Service Unavailable]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.danube.qa.testcases.LoginPageTest.loginPageTitleTest(LoginPageTest.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="com.danube.qa.testcases.LoginPageTest" name="loginPageTitleTest" time="5.028">
    <skipped/>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="com.danube.qa.testcases.LoginPageTest" name="loginPageTitleTest" time="4.789">
    <skipped/>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="com.danube.qa.testcases.LoginPageTest" name="loginPageTitleTest" time="4.686">
    <skipped/>
  </testcase> <!-- loginPageTitleTest -->
</testsuite> <!-- com.danube.qa.testcases.LoginPageTest -->
